### ISSUE TITLE
Port code to VS2015

### ISSUE THREAD

**Issue by ryan-de-boer** [dotnetinstaller/dotnetinstaller#109]
We use VS2015, and it would be useful if dotNetInstaller could be built by VS2015. I noticed the sln format was for VS2005, and I verified it can compile in VS2008 without changes (but not VS2015).

I ported the code to compile in VS2015 except the managed c++ CabLib library (and release mode only at the moment). The CabLib library uses the old clr syntax which is no longer supported, and it looked like it would take awhile to port to the new syntax (and error prone when you don't know how to test it). So I used a precompiled binary for CabLib (built with VS2008) and got everything else to compile in VS2015 (release mode only at the moment). So now I can make changes with just VS2015.

I can help you port to VS2015 if it is a feature you would like. One tricky step was fixing ___std_terminate and 'eh vector' linker errors, but luckily I found this german webpage solution:
http://www.speedproject.de/2015/05/12/visual-studio-2015-und-die-universal-crt/
(google translate does a good job at converting it to english).

**Comment by icnocop** [comment]
The reason why dotNetInstaller requires Visual Studio 2005 to build is because Visual Studio 2005 is "the last version to be able to target Windows 98, Windows Me and Windows NT 4.0 for C++ applications."[1] If we upgrade and require to build using Visual Studio 2015, then we lose support for running on those operating systems.

[1] https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#2005

**Comment by ryan-de-boer** [comment]
OK, thanks for the reply. It makes sense to keep it in VS2005 format while we want to support those other operating systems.
Its great to see dotNetInstaller is still in active development (the old VS2005 format shocked me a little, and I thought maybe it was no longer under development).
If other people need to compile it in VS2015, I suppose we could create a fork and put the changes in there (but the official one will get the official updates). Supporting both VS2005 and VS2015 in a single repo could be tricky and annoying to maintain.
Thanks for having this open source, it allows us to make minor changes fairly easy.

**Comment by dblock** [comment]
I thought about 5 years ago that we could drop Windows 98 support, but found out that there were actual users (!). I think it's time though.

**Comment by icnocop** [comment]
After installing [Wix Toolset Visual Studio 2015 Extension](https://marketplace.visualstudio.com/items?itemName=RobMensching.WixToolsetVisualStudio2015Extension) and [Microsoft Visual Studio 2015 Installer Projects Extension](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.MicrosoftVisualStudio2015InstallerProjects), Visual Studio 2015 was able to perform a one-way upgrade of `dni.sln`.
