### ISSUE TITLE
InstallerLinker.exe without .NET 3.5 installed

### ISSUE THREAD

**Issue by rr-media** [dotnetinstaller/dotnetinstaller#113]
Hi guys,

I was trying to run InstallerLinker.exe on the box without .NET 3.5 installed but had no luck.
I've added InstallerLinker.exe.config file with 4.5 runtime allowed but now it fails with 

_ERROR: Could not load file or assembly 'CabLib.dll' or one of its dependencies.
A dynamic link library (DLL) initialization routine failed. (Exception from HRES
ULT: 0x8007045A)_

Is it strict requirement to have .NET 3.5 installed? 
Does anyone have any work-around to run under .NET 4.5?

Thanks in advance

**Comment by dblock** [comment]
It has been a while... we haven't done a release since 2015! Not sure why this would happen, it's possible that the Cablib assembly proxy is marked in a way that doesn't work with other runtimes. If you dig it up I'll take pull requests.

**Comment by icnocop** [comment]
I think https://github.com/dblock/dotnetinstaller/pull/117 resolves this issue as well.

**Comment by icnocop** [comment]
Please try again with a 3.x release.

If the issue persists, please open a new issue with steps to reproduce.

Thank you.
