### ISSUE TITLE
Move DNI into an org?

### ISSUE THREAD

**Issue by dblock** [dotnetinstaller/dotnetinstaller#118]
@ramiabughazaleh Should I move this into an org to reduce bus factor? Currently I am the only one who can add repo collaborators.

**Comment by icnocop** [comment]
That's fine by me.

Thank you!

**Comment by dblock** [comment]
Done.

https://github.com/dotnetinstaller/dotnetinstaller

Old URLs will redirect. Some docs need to be updated.
