### ISSUE TITLE
How to place user controls(browse, license agreement) using htmlinstaller index.html?

### ISSUE THREAD

**Issue by GunzBlazing** [dotnetinstaller/dotnetinstaller#119]
Is it possible to control the placement of user controls in index.html of htmlinstaller? It seems like the user controls get plopped on top of everything instead of nicely placed in the html.

**Comment by GunzBlazing** [comment]
Alternatively is there a way to disable resizing of the htmlinstaller window? I placed two user controls manually in the dialog but since they don't scale with the rest of the window, I want to disable resizing of the window so the controls stay put.

**Comment by icnocop** [comment]
To disable resizing of the htmlInstaller window, set the `width` and `height` CSS properties of the `body` element to a specific width and height.

For example,
```
body
{
	width: 600px;
	height: 400px;
}
```

**Comment by icnocop** [comment]
To change the layout from a vertical stack to a horizontal stack, you can set the `flow` CSS property to `horizontal`.

For example:
style.css
```
#main /* main section: contains leftbar and rightbar */
{ 
	width:100%%; 
	height:100%%; 
	border: 1px dotted blue; 
	flow:horizontal; 
} 
#leftbar 
{ 
	margin:6px; 
	padding:2px;
	width:120px; 
	height:100%%;
	border: 1px solid black; 
	text-align:center;
} 
#rightbar 
{ 
	margin:6px; 
	text-align:center;
	width:100%%; 
	padding: 50%% 2px; /* place its content in the middle*/ 
	border: 1px solid red; 
}
```
index.html
```
<html>
<head>
    <style type="text/css">
        @import url(style.css) screen;
    </style>
</head>
<body>
    <div id="main">
        <div id="leftbar">
            <p>Left sidebar content</p>
        </div>
        <div id="rightbar">
            <p>Right content.</p>
        </div>
    </div>
</body>
</html>
```

This was adapted from the HTMLayout samples in the source code here:
.\ThirdParty\HTMLayoutSDK\html_samples\generic\sidebars.htm
