### ISSUE TITLE
Conditionals to run the prerequisite installations.

### ISSUE THREAD

**Issue by maliutin** [dotnetinstaller/dotnetinstaller#122]
Can I add conditionals which are checked before running prerequisite installations?

For example, it needs to Excel x86. And if the condition is met, then run the prerequisite installations.
It means the root node "Config File" should have the active menu items `Add->Checks->Installed ...`

**Comment by icnocop** [comment]
I think maybe the best approach is to define something like this:
```
<installedcheckoperator type="Or" description="Install if Excel add-in IS NOT installed">
        <installedcheck path="SOFTWARE\Microsoft\My Excel add-in for example" fieldname="Installed" fieldvalue="1" defaultvalue="False" fieldtype="REG_DWORD" comparison="match" rootkey="HKEY_LOCAL_MACHINE" wowoption="NONE" type="check_registry_value" description="My Excel add-in IS Installed" />
        <installedcheckoperator type="Not" description="Excel IS NOT Installed">
          <installedcheck path="SOFTWARE\Microsoft\Excel for example" fieldname="Installed" fieldvalue="1" defaultvalue="False" fieldtype="REG_DWORD" comparison="exists" rootkey="HKEY_LOCAL_MACHINE" wowoption="NONE" type="check_registry_value" description="Excel IS Installed" />
        </installedcheckoperator>
      </installedcheckoperator>
```

Basically, "My Excel add-in" is installed when: "My Excel add-in IS Installed" OR "Excel IS NOT Installed".

I haven't tested it though.

I think this question would have been better asked in the Google groups discussion forum:
https://groups.google.com/forum/#!forum/dotnetinstaller

Thank you.
