### ISSUE TITLE
Boostrapper displays an error after an intermediate reboot when installing from a CD

### ISSUE THREAD

**Issue by telemak68** [dotnetinstaller/dotnetinstaller#137]
After integrating the .NET Framework 4.8 setup prerequisite and performing installation from a CD, DotNetInstaller displays a reboot prompt. Yet, after reboot it displays an error message:
“missing Setup\ en-US_x64.xml component”.

The log file contains following string:

Writing HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run\setup_x64.exe: "D:\Setup\setup_x64.exe" /ConfigFile Setup\en-US_x64.xml /Reboot

It seems that drive letter  is missing in the xml path reference.

The .NET Framework 4.8 is defined like this:

```xml
 <component executable="#APPPATH\Prerequisites\ndp48-x86-x64-allos-enu.exe" executable_silent="" executable_basic="" install_directory="" responsefile_source="" responsefile_target="" responsefile_format="none" uninstall_executable="" uninstall_executable_silent="" uninstall_executable_basic="" uninstall_responsefile_source="" uninstall_responsefile_target="" returncodes_success="" returncodes_reboot="1641,3010" exeparameters="/passive /norestart" exeparameters_basic="/passive /norestart" exeparameters_silent="/q" uninstall_exeparameters="" uninstall_exeparameters_basic="" uninstall_exeparameters_silent="" id="Microsoft .NET Framework 4.8 Full" display_name="Microsoft .NET Framework 4.8" uninstall_display_name="" os_filter="" os_filter_min="win7sp1" os_filter_max="" os_filter_lcid="" type="exe" installcompletemessage="" uninstallcompletemessage="" mustreboot="False" reboot_required="Setup will reboot now. Press OK to reboot." must_reboot_required="True" failed_exec_command_continue="Failed to install %s." allow_continue_on_error="False" default_continue_on_error="False" required_install="True" required_uninstall="False" selected_install="True" selected_uninstall="False" note="" processor_architecture_filter="" status_installed="" status_notinstalled="" supports_install="True" supports_uninstall="False" show_progress_dialog="True" show_cab_dialog="False">
      <installedcheck path="SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full" fieldname="Release" fieldvalue="528040" defaultvalue="False" fieldtype="REG_DWORD" comparison="version" rootkey="HKEY_LOCAL_MACHINE" wowoption="NONE" type="check_registry_value" description="Installed Check" />
</component>
```

Is it a bug or some adjustments in the component markup can be done to enable resuming installation after reboot?

**Comment by icnocop** [comment]
Hi @telemak68 .

The XML code for "The .NET Framework 4.8 is defined like this" is not visible in the GitHub issue.

Can you try again please?

Thank you.

**Comment by telemak68** [comment]
Hello @icnocop, 

Thank you very much for your prompt reply. I can see the XML code of the .NET Framework 4.8 component in my browser. Let me specifiy it once again:

 <component executable="#APPPATH\Prerequisites\ndp48-x86-x64-allos-enu.exe" executable_silent="" executable_basic="" install_directory="" responsefile_source="" responsefile_target="" responsefile_format="none" uninstall_executable="" uninstall_executable_silent="" uninstall_executable_basic="" uninstall_responsefile_source="" uninstall_responsefile_target="" returncodes_success="" returncodes_reboot="1641,3010" exeparameters="/passive /norestart" exeparameters_basic="/passive /norestart" exeparameters_silent="/q" uninstall_exeparameters="" uninstall_exeparameters_basic="" uninstall_exeparameters_silent="" id="Microsoft .NET Framework 4.8 Full" display_name="Microsoft .NET Framework 4.8" uninstall_display_name="" os_filter="" os_filter_min="win7sp1" os_filter_max="" os_filter_lcid="" type="exe" installcompletemessage="" uninstallcompletemessage="" mustreboot="False" reboot_required="Setup will reboot now. Press OK to reboot." must_reboot_required="True" failed_exec_command_continue="Failed to install %s." allow_continue_on_error="False" default_continue_on_error="False" required_install="True" required_uninstall="False" selected_install="True" selected_uninstall="False" note="" processor_architecture_filter="" status_installed="" status_notinstalled="" supports_install="True" supports_uninstall="False" show_progress_dialog="True" show_cab_dialog="False">
      <installedcheck path="SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full" fieldname="Release" fieldvalue="528040" defaultvalue="False" fieldtype="REG_DWORD" comparison="version" rootkey="HKEY_LOCAL_MACHINE" wowoption="NONE" type="check_registry_value" description="Installed Check" />
</component>
[NetFw48Component.txt](https://github.com/dotnetinstaller/dotnetinstaller/files/4485974/NetFw48Component.txt)

I have also uploaded the NetFw48Component.txt with the corresponding XML code.
Thanks in advance for your assistance!

**Comment by icnocop** [comment]
Can you upload the dotNetInstaller log file please?

Thank you.

**Comment by icnocop** [comment]
I'm interested to know the command line used to run the bootstrapper.
DotNetInstaller should use the same command line to re-run the bootstrapper after the reboot.
So if a drive letter was specified, then it should also be included in the registry.

Was the setup bootstrapper run with the following command line:
` "D:\Setup\setup_x64.exe" /ConfigFile Setup\en-US_x64.xml /Reboot`?

**Comment by telemak68** [comment]
Hello icnocop,

Thank you for your insightful considerations.

Please find attached the DNI log file.
[DNI.log](https://github.com/dotnetinstaller/dotnetinstaller/files/4486408/DNI.log)

In my CD browser, I am setting a current working directory and run bootstrapper with the following command line:

Setup\setup_x64.exe" /ConfigFile Setup\en-US_x64.xml

I cannot specify the drive letter, because it may be different on various systems.

**Comment by icnocop** [comment]
> I am setting a current working directory 

How are you doing this?

I'm thinking you can use the same mechanism to get the drive letter.

For example, running this command in a batch file may resolve your issue:
`"%CD%\Setup\setup_x64.exe" /ConfigFile "%CD%\Setup\en-US_x64.xml"`

Thank you.

**Comment by telemak68** [comment]
Hello Rami, 

Many thanks for your suggestions. I will try to check if using variables will be possible in the CD Browser commands and will notify you about obtained results. I appreciate your help and support!

**Comment by telemak68** [comment]
Hi Rami,

I have accomplished a new build and tested a DNI behavior after reboot following your recommendations. With updated references to the configuration files, the issue has been resolved.

Thank you very much for your assistance!

**Comment by icnocop** [comment]
You're welcome. I'm glad it worked! 😄
