### ISSUE TITLE
Install check to parse directory names as version numbers for comparison

### ISSUE THREAD

**Issue by icnocop** [dotnetinstaller/dotnetinstaller#153]
One way to detect if a specific version of .NET Core is installed is by checking for the presence of a directory in `%PROGRAMFILES%\dotnet\shared\Microsoft.NETCore.App` with the version number as the directory name.

For example, the following installed check determines if .NET Core 3.1.10 is installed:
```
<installedcheck
  type="check_directory"
  path="%PROGRAMFILES%\dotnet\shared\Microsoft.NETCore.App\3.1.10" />
```

However, a requirement of an application could allow for any .NET Core 3.1.x to be installed in order to run, and dotnetinstaller doesn't currently have an easy way to do this other than having an `installedcheck` for each specific version.

I would like to add support for an additional `comparison` attribute for the `check_directory` `installedcheck` type which will allow this type of check, similar to the `check_file` and `check_registry_value` types.

The default value will be `exists` to support backwards compatibility.

For example,
```
<installedcheck
  type="check_directory"
  comparison="version_ge"
  path="%PROGRAMFILES%\dotnet\shared\Microsoft.NETCore.App"
  value="3.1.10" />
```

This will enumerate all sub directories in `path`, parse the names of the sub directories as version numbers, and determine if any version number is greater than or equal to the value specified in the `value` attribute.

![image](https://user-images.githubusercontent.com/507649/176766948-4bd5e961-c35a-48ba-9c0f-c00e83f9e951.png)

**Comment by dblock** [comment]
The directory part makes sense.

For semantic versioning that's a separate feature, I think you should decide whether you want to throw errors, warnings or do nothing when you encounter a version like `7.0.0-preview.5.22301.12` in general. Maybe just parse it and fail comparisons when one of the versions has a `-preview.5.22301.12` qualifier?

**Comment by icnocop** [comment]
I decided to incorporate semantic versioning support after all. 😉
